modules/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'
urlpatterns = [
	path(
		route='',
		view=IndexView.as_view(),
		name='index'
	),
]

modules/polls/urls.py
from django.urls import path
from .views import (
	IndexView,
	PreguntaDetail,
	PreguntaCreate,
	PreguntaUpdate,
	PreguntaDelete,
)


app_name = 'polls'
urlpatterns = [
    path(
    	route='',
    	view=IndexView.as_view(),
    	name='index'
    ),
    path(
    	route='detalle/<int:pk>',
    	view=PreguntaDetail.as_view(),
    	name='detalle'
    ),
    path(
    	route='pregunta/create/',
    	view=PreguntaCreate.as_view(),
    	name='pregunta_create'
    ),
    path(
    	route='pregunta/update/<int:pk>',
    	view=PreguntaUpdate.as_view(),
    	name='pregunta_update'
    ),
    path(
    	route='pregunta/delete/<int:pk>',
    	view=PreguntaDelete.as_view(),
    	name='pregunta_delete'
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('modules.core.urls')),
	path('polls/', include('modules.polls.urls')),
]

modules/core/models.py
from django.db import models

# Create your models here.

modules/polls/models.py
from django.db import models


LISTA_CAMISAS = (
	('S', 'Pequeña'),
	('M', 'Mediano'),
	('L', 'Largo'),
	('XL', 'Extra largo'),
)

# Creamos la tabla pregunta
class Pregunta(models.Model):
	titulo = models.CharField(max_length=200, help_text='Queremos que guardes el titulo de la pregunta')
	creacion = models.DateTimeField(auto_now_add=True)
	modificacion = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name = 'pregunta'
		verbose_name_plural = 'preguntas'
		# Esto ordena las preguntas por fecha donde trae las ultimas primero.
		ordering = ['-creacion']

	def __str__(self):
		return '%s' % (self.titulo)


class Opcion(models.Model):
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
	titulo = models.CharField(max_length=200, help_text='Queremos que guardes el titulo de la opcion')
	votos = models.IntegerField(help_text='Votos de la opcion')

	class Meta:
		verbose_name = 'opcion'
		verbose_name_plural = 'opciones'
		ordering = ['votos']

	def __str__(self):
		return '%s' % (self.titulo)


class Persona(models.Model):
	nombre = models.CharField(max_length=30)
	apellido = models.CharField(max_length=30)
	talle = models.CharField(max_length=1, choices=LISTA_CAMISAS)

	class Meta:
		db_table = 'personas'


class Talle(models.Model):
	nombre = models.CharField(max_length=30)

	def __str__(self):
		return '%s' % (self.nombre)


class Autoridad(models.Model):
	nombre = models.CharField(max_length=50)
	talle = models.ForeignKey(Talle, on_delete=models.CASCADE)

	def __str__(self):
		return '%s' % (self.nombre)

	class Meta:
		verbose_name_plural = 'autoridades'

modules/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexView(TemplateView):
	template_name = 'index.html'

modules/polls/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Pregunta


class IndexView(LoginRequiredMixin, ListView):
	model = Pregunta
	template_name = 'pregunta/index.html'
	context_object_name = 'preguntas'


class PreguntaDetail(LoginRequiredMixin, DetailView):
	model = Pregunta
	template_name = 'pregunta/detalle.html'
	context_object_name = 'pregunta'


# Sirve para crear un formulario y dar de alta una Pregunta fuera del admin
class PreguntaCreate(LoginRequiredMixin, CreateView):
	model = Pregunta
	fields = ['titulo']
	template_name = 'pregunta/create.html'
	success_url = reverse_lazy('polls:index')


class PreguntaUpdate(LoginRequiredMixin, UpdateView):
	model = Pregunta
	fields = ['titulo']
	template_name = 'pregunta/update.html'
	success_url = reverse_lazy('polls:index')


class PreguntaDelete(LoginRequiredMixin, DeleteView):
	model = Pregunta
	template_name = 'pregunta/delete.html'
	success_url = reverse_lazy('polls:index')

modules/core/templates/index.html
{% extends 'base.html' %}

modules/polls/templates/pregunta/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}Pregunta: create{% endblock titulo %}
{% block contenido %}
<div class="container">
	<div class="row">
		<div class="col-md-6 mt-3">
			<form action="" method="post">
				{% csrf_token %}
				{{ form|crispy }}
				<input class="btn btn-sm btn-success" type="submit" value="Crear pregunta">
			</form>
			<p class="lead mt-3">(*) Campos obligatorios</p>
		</div>
	</div>
</div>
{% endblock contenido %}

modules/polls/templates/pregunta/delete.html
{% extends 'base.html' %}
{% block titulo %}Pregunta {{ pregunta.id }}{% endblock titulo %}
{% block contenido %}
	<div class="container">
		<div class="row">
			<div class="col-md-8 mt-3">
				<form method="post">{% csrf_token %}
					<p>Eliminar: <strong>{{ object }}</strong></p>
					<input class="btn btn-sm btn-danger" type="submit" value="Confirmar">
				</form>
			</div>
		</div>
	</div>
{% endblock contenido %}

modules/polls/templates/pregunta/detalle.html
{% extends 'base.html' %}
{% block titulo %}Pregunta {{ pregunta.id }} {% endblock titulo %}
{% block contenido %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<p><strong>Titulo:</strong> {{ pregunta.titulo }}</p>
			<p><strong>Fecha:</strong> {{ pregunta.creacion|date:"d-m-Y" }}</p>
		</div>
	</div>
	<div class="row">
		<div class="col mt-3">
			{% if pregunta.opcion_set.all %}
				<ul>
					{% for p in pregunta.opcion_set.all %}
					<li>{{ p.titulo }} ** voto: {{ p.votos }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<p class="lead">No hay votos para estar pregunta aun</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock contenido %}

modules/polls/templates/pregunta/index.html
{% extends 'base.html' %}
{% block titulo %}Encuestas{% endblock titulo %}
{% block contenido %}
<div class="container">
	<div class="row">
		<div class="col mt-2 mb-2">
			<h1>Lista de preguntas</h1>
			<a href="{% url 'polls:pregunta_create' %}" class="btn btn-sm btn-dark mt-2 mb-2">Crear pregunta</a>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<table class="table text-center">
				<thead>
					<tr>
						<th>#</th>
						<th>Nombre</th>
						<th>Fecha</th>
						<th>Modificacion</th>
						<th>Detalle</th>
						<th>Editar</th>
						<th>Eliminar</th>
					</tr>
				</thead>
				<tbody>
					{% for pregunta in preguntas %}
					<tr>
						<th>{{ pregunta.id }}</th>
						<td>{{ pregunta.titulo }}</td>
						<td>{{ pregunta.creacion }}</td>
						<td>{{ pregunta.modificacion }}</td>
						<td><a href="{% url 'polls:detalle' pregunta.id %}"><i class="far fa-eye"></i></a></td>
						<td><a href="{% url 'polls:pregunta_update' pregunta.id %}"><i class="fas fa-pencil-alt"></i></a></td>
						<td><a href="{% url 'polls:pregunta_delete' pregunta.id %}"><i class="far fa-trash-alt"></i></a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock contenido %}

modules/polls/templates/pregunta/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo %}Actualizar: {{ pregunta.id }}{% endblock titulo %}
{% block contenido %}
<div class="container">
	<div class="row">
		<div class="col mt-3">
			<form method="post">{% csrf_token %}
				{{ form|crispy }}
				<input class="btn btn-sm btn-info" type="submit" value="Actualizar">
			</form>
		</div>
	</div>
</div>
{% endblock contenido %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <title>{% block titulo %}{% endblock titulo %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'core:index' %}">MySite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ request.user.username|capfirst }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'logout'%}">Salir</a>
              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login'%}">Ingresar</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block contenido %}{% endblock contenido %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>